### ISSUE TITLE
[feat] Sale Domain 기능 구현

### ISSUE THREAD

**Issue by limjihoon99** [limjihoon99/SWCAMP_Team3#36]
## ✨ 구현 할 기능
- [x] 매물 등록
- [x] 매물 수정
- [x] 매물 삭제
- [x] 리스트 조회
- [x] 상세 조회

<br>

### 📕 레퍼런스

**Comment by henhen7** [comment]
### swagger 및 workbench 결과
<details>
<summary>매물 등록</summary>
<div markdown="1">

`매물등록 확인`
<img width="1395" alt="매물등록" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/ef2b5658-dd86-4a0e-90bf-21d306191479">

`제약조건 확인`
<img width="1302" alt="매물등록-오류조회" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/b82e3f61-5a81-4675-b13a-6f669a38ed04">

</div>
</details>

<details>
<summary>매물 수정</summary>
<div markdown="1">

`업데이트`
<img width="1400" alt="업데이트" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/35ce084f-ad04-4c52-8cf3-bb81115b9aa3">

`업데이트 결과`
<img width="1395" alt="업데이트 확인" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/0b358e42-0d92-43be-9ecc-99298e27671d">


</div>
</details>

<details>
<summary>매물 삭제</summary>
<div markdown="1">

`삭제`
<img width="1397" alt="삭제" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/127c3e0a-0aae-4b2e-840c-ca900711f569">

`삭제 결과`
<img width="1399" alt="삭제 확인" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/e44d6246-d4e5-4ab6-9c62-26544c9b13e0">


</div>
</details>

<details>
<summary>매물 조회</summary>
<div markdown="1">

`리스트 조회`
<img width="1399" alt="리스트조회" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/7d2f3e98-0e4c-4841-97d5-4b77df0d1c4f">


`상세 조회`
<img width="1404" alt="상세조회" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/387477e9-8d3d-4cdb-8ffa-428f08800948">


</div>
</details>

<details>
<summary>DB 조회</summary>
<div markdown="1">

`테이블 조회`
<img width="1003" alt="DB도 확인" src="https://github.com/limjihoon99/SWCAMP_Team3/assets/136338584/75056e78-dd0a-46f2-b8c9-72d0adf60fe2">


</div>
</details>

**Comment by henhen7** [comment]
### 추후 리팩토링 목표
- 등록시간, 수정시간 엔티티 상속
- 매물 정보에서 리뷰 수 카운트
- 필드별 상세 제약 조건 추가
- 각 기능별 호출 필드 추가(정보 추가)
- 클래스별 안쓰는 어노테이션 삭제
