### ISSUE TITLE
[test/#50] Review Domain Test

### ISSUE THREAD

**Issue by uzz99** [limjihoon99/SWCAMP_Team3#50]
## ✨ 테스트 할 기능
- [x] CreateReview
- [x] GetListReviews
- [x] GetDetailReview
- [x] UpdateReview
- [x] DeleteReview

<br>

### 📕 레퍼런스

**Comment by uzz99** [comment]
<details>
  <summary> 🟢 ReviewCreateTest</summary>

![1   리뷰 생성  ReviewCreateTest](https://github.com/user-attachments/assets/c190de30-1c30-4bc0-9b57-a280c8de1ade)

</details>

<details>
  <summary> 🟢  ReviewSaleNotFound</summary>

- 예외처리로 테스트 통과

![1   리뷰 생성  매물 없음 testCreateReviewSaleNotFound_exception](https://github.com/user-attachments/assets/4ed5fd63-821d-43e3-a8ce-3e319ec1581b)

</details>

<details>
  <summary>🟢 ReviewUserNotFound </summary>

- 예외처리로 테스트 통과

![1   리뷰 생성  유저 없음 testCreateReviewUserNotFound_exception](https://github.com/user-attachments/assets/7a90a4fb-ba67-4c2a-9e66-03c6b43645de)

</details>

**Comment by limjihoon99** [comment]
와.. 굳굳

**Comment by uzz99** [comment]
<details>
  <summary> 🟢 GetListReviewsTest: Success </summary>

![2   리뷰 전체 조회  testGetListReviews_success](https://github.com/user-attachments/assets/92d391b1-95c7-44cc-8ade-0d1f579873d1)


</details>

<details>
  <summary> 🔴   GetListReviewsTest: Fail</summary>

![2   리뷰 전체 조회  실패 testGetListReviews_fail](https://github.com/user-attachments/assets/d1df1297-cc16-4fe4-8f74-afaecfe5b532)

</details>

**Comment by uzz99** [comment]
<details>
  <summary> 🟢 GetReviewDetailTest</summary>

![3   리뷰 단건 조회  testGetReviewDetail](https://github.com/user-attachments/assets/625ad82f-1d88-4ebc-912d-e34a583bc44c)

</details>

<details>
  <summary>🟢 GetReviewDetailNotFound </summary>

- 예외처리로 테스트 통과

![3   리뷰 단건 조회  testGetReviewDetailNotFound_exception](https://github.com/user-attachments/assets/21200a00-abe7-49be-b52c-9867c2a6c478)


</details>

**Comment by uzz99** [comment]
<details>
  <summary> 🟢 UpdateReviewTest</summary>

- 정상 수정

![image](https://github.com/user-attachments/assets/15a414ef-648a-43fd-b3b7-60b0762c8f61)

</details>

<details>
  <summary> 🟢 UpdateReviewNotFound</summary>

-  예외처리로 테스트 통과

![4   리뷰 수정  testUpdateReviewNotFound_exception](https://github.com/user-attachments/assets/116b70b6-9391-4561-8c31-0546b2ff2a51)

</details>

<details>
  <summary> +) 🔴 UpdateReviewNotFound: Fail</summary>

- 예외처리 내용이 일치하지 않는 경우, 테스트 실패

![4   리뷰 수정  testUpdateReviewNotFound_fail](https://github.com/user-attachments/assets/6174266b-be70-457e-b86f-1142554d7571)

</details>

**Comment by uzz99** [comment]
<details>
  <summary> 🟢 DeleteReview</summary>

- 리뷰 정상 삭제

![5   리뷰 삭제  testDeleteReview_success](https://github.com/user-attachments/assets/28045a59-8a68-471f-b327-48957987bd27)

</details>

<details>
  <summary> 🟢 DeleteReviewNotFound</summary>

- 예외처리로 테스트 통과

![5   리뷰 삭제  testDeleteReviewNotFound_success](https://github.com/user-attachments/assets/10cc73ba-7ba9-44c2-8c2c-2bc9c493ac22)


</details>

**Comment by uzz99** [comment]
delete test code edit....ing

**Comment by uzz99** [comment]
삭제 시, 회원검증 추가(#59): 테스트코드 수정

<details>
  <summary> 🔴 DeleteReview: fail</summary>

- 리뷰 삭제 불가
- 작성하지 않은 사용자가 삭제 시 fail

![5 리뷰 삭제  회원검증 추가](https://github.com/user-attachments/assets/aa65ae83-6b6a-4220-804d-e4372fa53ab2)

</details>

<details>
  <summary> 🟢 DeleteReviewNotFound</summary>

- 예외처리로 테스트 통과

![5 리뷰 삭제  회원검증 exception](https://github.com/user-attachments/assets/0cf06ea5-e0c2-4bc4-b712-617e8f166861)

</details>
